# Generated by Django 4.1.7 on 2023-04-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crudeoil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudeOil',
        ),
    ]
