# Generated by Django 4.1.7 on 2023-04-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_eiadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EIAData',
        ),
    ]
