# Generated by Django 4.1.7 on 2023-04-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_eiadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrudeOil',
        ),
    ]
